import { Inter } from 'next/font/google'
import './globals.css'
import ChakraProviderLayout from './layouts/chakra-provider'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <ChakraProviderLayout>
            <body className={inter.className}>{children}</body>
        </ChakraProviderLayout>
      </html>
  )
}
